[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "khmerlang"
version = "1.0.0"
description = "KhmerLang (ភាសាខ្មែរ) — The Khmer Programming Language"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Seng Vengchhuong" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Interpreters",
]

[project.scripts]
khmer = "khmer_lang.cli:main"
